// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:e_learning_mobile/constants/constants.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: fireBaseKey,
    appId: fireBaseAppId,
    messagingSenderId: '977360375759',
    projectId: 'speekiai',
    authDomain: 'speekiai.firebaseapp.com',
    storageBucket: 'speekiai.appspot.com',
    measurementId: 'G-MSFJJCW34X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: fireBaseKey,
    appId: fireBaseAppId,
    messagingSenderId: '977360375759',
    projectId: 'speekiai',
    storageBucket: 'speekiai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: fireBaseKey,
    appId: fireBaseAppId,
    messagingSenderId: '977360375759',
    projectId: 'speekiai',
    storageBucket: 'speekiai.appspot.com',
    androidClientId:
        '977360375759-47gtabneb01e4a0ufc33tkbv8ovo6a9f.apps.googleusercontent.com',
    iosClientId:
        '977360375759-gkhut3b9plf5t7j1qqn1m2hb426on6u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: fireBaseKey,
    appId: fireBaseAppId,
    messagingSenderId: '977360375759',
    projectId: 'speekiai',
    storageBucket: 'speekiai.appspot.com',
    androidClientId:
        '977360375759-47gtabneb01e4a0ufc33tkbv8ovo6a9f.apps.googleusercontent.com',
    iosClientId:
        '977360375759-gkhut3b9plf5t7j1qqn1m2hb426on6u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: fireBaseKey,
    appId: fireBaseAppId,
    messagingSenderId: '977360375759',
    projectId: 'speekiai',
    authDomain: 'speekiai.firebaseapp.com',
    storageBucket: 'speekiai.appspot.com',
    measurementId: 'G-JVRLRB6J0J',
  );
}
